version: "3.9"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - TELEGRAM_LOGIN=${TELEGRAM_LOGIN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    depends_on:
      - mongodb
    container_name: ${SERVICE_NAME}_app_prod
    env_file: .env
    networks:
      - cryptobot-gift-network

  mongodb:
    image: mongo:latest
    restart: always
    container_name: ${SERVICE_NAME}_mongodb_prod
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - cryptobot-gift:/data/db
    networks:
      - cryptobot-gift-network

volumes:
  cryptobot-gift:
    external: true

networks:
  cryptobot-gift-network:
